os: Visual Studio 2015
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- IF EXIST "..\PearXLib" ( rd /s /q "..\PearXLib" )
- git clone https://github.com/mrAppleXZ/PearXLib.git ../PearXLib